from __future__ import annotations

from dataclasses import dataclass

from agent_core.apps.deepdive.tools import SourceTracker


@dataclass
class DeepdiveReport:
    topic: str
    markdown: str
    sources: SourceTracker
    total_steps: int
    total_tokens: int
    total_cost_usd: float
    duration_seconds: float
    session_id: str | None = None

    def render_with_metadata(self) -> str:
        footer = (
            "\n\n---\n\n"
            f"*Generated by deepdive: {self.total_steps} steps, "
            f"{self.total_tokens:,} tokens, "
            f"${self.total_cost_usd:.4f}, "
            f"{self.duration_seconds:.1f}s*"
        )
        return self.markdown + self._render_sources_appendix() + footer

    def _render_sources_appendix(self) -> str:
        if not self.sources.sources:
            return ""
        lines = ["", "", "## All Consulted Sources", ""]
        for index, source in self.sources.numbered_sources():
            marker = "✓" if source.fetch_count > 0 else "○"
            label = source.title or source.url
            lines.append(f"{index}. {marker} [{label}]({source.url})")
        lines.append("")
        lines.append("*✓ = fetched with http_get, ○ = seen in search results only*")
        return "\n".join(lines)
